services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=pokedecks'
      - 'POSTGRES_USER=docker'
      - 'POSTGRES_PASSWORD=docker'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    networks:
      - 'pokedecks-network'

volumes:
  pgdata:

networks:
  pokedecks-network: