spring:
  application:
    name: 'PokeDecks'
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/pokedecks
    username: docker
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

server:
  port: 8080
